### ISSUE TITLE
django: move all cast_decimalfield and all Decimal->float casts into dbapi

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner-django#224]
Coming here from PR #223, this issue is a TODO to move all the code that casts decimal.Decimal to float, moving it from spanner/django/* into spanner/ as requested in https://github.com/orijtech/spanner-orm/pull/223#pullrequestreview-335625038.

On trying to move one thing from that code site, it produced a bunch of test failures as per https://travis-ci.com/orijtech/spanner-orm/builds/142024493
![Screen Shot 2019-12-21 at 5 14 57 PM](https://user-images.githubusercontent.com/4898263/71315562-6ecc0900-2415-11ea-94cf-b1d99d570576.png)

so in the interest of scarce time, this issue is meant to investigate and finish up that consolidation work.

**Comment by timgraham** [comment]
`DecimalField` isn't supported because Spanner doesn't yet have a NUMERIC type. The casting is a workaround to make DecimalField work with float64 so Django's test suite can run. That'll probably be obsolete once Spanner adds a NUMERIC type.
