### ISSUE TITLE
django: implement dbshell

### ISSUE THREAD

**Issue by timgraham** [googleapis/python-spanner-django#236]
The [`manage.py dbshell`](https://docs.djangoproject.com/en/stable/ref/django-admin/#dbshell) command is [unimplemented](https://github.com/orijtech/spanner-orm/pull/235).

I'm not sure if there's an executable that provides a SQL interface. https://medium.com/@yfuruyama/spanner-cli-the-cloud-spanner-command-line-interface-c8d2a171f84b is the closest thing I found.

**Comment by asthamohta** [comment]
Closing this issue as dbshell is not implemented for Django currently: https://github.com/googleapis/python-spanner-django/pull/235
