### ISSUE TITLE
django: Meta.order_with_respect_to column name is incompatible with Spanner

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner-django#396]
Tried running contenttypes_tests and it failed with
```shell
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.GoogleAPICallError: None Column name not valid: contenttypes_tests_answer._order.
```

where the generated SQL look like this
```sql
CREATE TABLE contenttypes_tests_answer (
   id INT64 NOT NULL,
   text STRING(200) NOT NULL,
   content_type_id INT64 NOT NULL,
   object_id INT64 NOT NULL,
   _order INT64 NOT NULL
) PRIMARY KEY(id)
```

even trying backticks on the column name doesn't fix the problem `_order`, per
![Screen Shot 2020-03-29 at 9 31 50 PM](https://user-images.githubusercontent.com/4898263/77875368-b88e7180-7204-11ea-83b8-dac5155911ef.png)

and then without the backticks
![Screen Shot 2020-03-29 at 9 31 36 PM](https://user-images.githubusercontent.com/4898263/77875380-c04e1600-7204-11ea-92e9-6482ff2d1049.png)

Over all this is a broader issue of spanner not supporting column names starting with special characters.

**Comment by timgraham** [comment]
I patched the Django fork to allow running `contenttypes_tests` and `order_with_respect_to` which would otherwise crash due to the invalid column name.
```diff
diff --git a/django/db/models/fields/proxy.py b/django/db/models/fields/proxy.py
index 0ecf04a333..6439f21e42 100644
--- a/django/db/models/fields/proxy.py
+++ b/django/db/models/fields/proxy.py
@@ -14,5 +14,8 @@ class OrderWrt(fields.IntegerField):
 
     def __init__(self, *args, **kwargs):
         kwargs['name'] = '_order'
+        # Spanner doesn't support column names starting with _. This allows
+        # the test to run.
+        kwargs['db_column'] = 'x_order'
         kwargs['editable'] = False
         super().__init__(*args, **kwargs)
```

**Comment by asthamohta** [comment]
This is a document limitations here: https://github.com/googleapis/python-spanner-django/blob/main/docs/limitations.rst which we do not plan on adding support for currently hence closing the issue
