### ISSUE TITLE
django-test-suite: "Permission errors are not swallowed" for file_uploads.tests.DirectoryCreationTests.test_readonly_root

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner-django#407]
Just noticed as the consistent sole failure after moving to Google Cloud Build:
[Full build listing](https://source.cloud.google.com/results/invocations/97db129d-7b50-4850-b255-b443b595ef27/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner-django%2Fpresubmit%2Fpresubmit/log)

and in particular the [test failure](https://source.cloud.google.com/results/invocations/7f7bfc9c-baf8-4030-a870-217e52f331c7/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner-django%2Fpresubmit%2Fworker_1/log)
```shell
======================================================================
FAIL: test_readonly_root (file_uploads.tests.DirectoryCreationTests)
Permission errors are not swallowed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmpfs/src/github/python-spanner-django/django_tests/django/tests/file_uploads/tests.py", line 548, in test_readonly_root
    self.obj.testfile.save('foo.txt', SimpleUploadedFile('foo.txt', b'x'), save=False)
AssertionError: PermissionError not raised

----------------------------------------------------------------------
Ran 50 tests in 133.498s

FAILED (failures=1, skipped=15)
```

**Comment by timgraham** [comment]
It seems that the `os.chmod` in that test isn't having an effect. This is probably an issue with Kokoro. It's certainly not a bug in django-spanner.

**Comment by odeke-em** [comment]
Thank you @timgraham! Let's perhaps add a condition in features.py say
```python
if os.environ.get('KOKORO_JOB_NAME'):
    # Kokoro fails to accept an os.Chmod.
    skip_tests += ('file_uploads.tests.DirectoryCreationTests.test_readonly_root',)
```

and then we can close out this issue.
