### ISSUE TITLE
django-test-suite: migration_test_data_persistence.tests.MigrationDataNormalPersistenceTestCase failure

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner-django#408]
Just noticed as the sole failure after moving to Google Cloud Build:
[Full build listing](https://source.cloud.google.com/results/invocations/492627f5-7fa7-4506-978e-ddc4e9456ab4/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner-django%2Fpresubmit%2Fpresubmit/log)

and in particular the [test failure](https://source.cloud.google.com/results/invocations/81c963da-2ed6-4ce3-bd98-82594caf869f/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner-django%2Fpresubmit%2Fworker_1/log)
```shell
======================================================================
FAIL: test_persistence (migration_test_data_persistence.tests.MigrationDataNormalPersistenceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmpfs/src/github/python-spanner-django/django_tests_1/django/tests/migration_test_data_persistence/tests.py", line 28, in test_persistence
    self.assertEqual(
AssertionError: 0 != 1

----------------------------------------------------------------------
```

To be investigated, as am currently prioritizing getting the tests moved and passing on Google Cloud Build.

**Comment by timgraham** [comment]
I don't see a reason why moving the tests to Kokoro would cause this failure. It might be that this test isn't completely isolated and fails depending on which tests it's run with in parallel. This failure may reoccur but for now I removed the skip.
