### ISSUE TITLE
performance testing harness

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner-django#438]
I've been requested that we should set up a performance test harness. Very tricky one because we can't directly measure against the client libraries. An apples to apples comparison would perhaps
be using spanner_dbapi, but django-spanner itself is tricky to set up.

**Comment by odeke-em** [comment]
A while back, I create a benchmarking repository for spanner_dbapi vs the Python client library, at https://github.com/orijtech/spanner-benchmarking
which uses OpenCensus and Prometheus to visualize results e.g.

![Screen Shot 2020-04-22 at 2 50 17 PM](https://user-images.githubusercontent.com/4898263/80037556-a53f9080-84a8-11ea-988d-225fc58bc134.png)

**Comment by odeke-em** [comment]
I've spun up this code https://gist.github.com/odeke-em/929d308f1fb80a1661d2e3ccb6a7b58b which produces ineresting results when comparing benchmarks https://gist.github.com/odeke-em/929d308f1fb80a1661d2e3ccb6a7b58b#file-results-md
```shell
name                old time/op  new time/op  delta
ReadOnly            93.7ms ±18%  87.6ms ±11%   -6.50%  (p=0.007 n=20+18)
ReadWrite           87.5ms ±13%  91.9ms ±39%     ~     (p=0.153 n=96+83)
CreateDestroyTable   47.3s ±20%   17.7s ±47%  -62.49%  (p=0.002 n=6+6)
```

**Comment by prakhargurunani** [comment]
@odeke-em Can you tell me more about how to return results (display them in terminal or store them somewhere)

**Comment by asthamohta** [comment]
#675 We have also done benchmark testing here where Spanner vs Django performance are tested
