### ISSUE TITLE
Use nox instead of tox for testing

### ISSUE THREAD

**Issue by IlyaFaer** [googleapis/python-spanner-django#459]
I've noticed that Django Spanner uses `tox` as a test base. Other Google Python packages are using `nox` with generated noxfiles (with lint, docs, coverage, system and unit testing sessions) - see [python-spanner noxfile.py](https://github.com/googleapis/python-spanner/blob/master/noxfile.py) as an example. If we're going to move this API to the original Python Spanner client, we probably should use `nox` here to stay in touch with the original test configurations.

**Comment by c24t** [comment]
If using nox helps us move faster here then it may be worth it to switch, but not otherwise. Tox seems to have much better adoption outside of google-owned repos.

**Comment by c24t** [comment]
Done as of #480.
