### ISSUE TITLE
connect() surface issues

### ISSUE THREAD

**Issue by IlyaFaer** [googleapis/python-spanner-django#460]
Looking at `connect()` function, there are several things which are raising questions.

**project arg:**
 `project` is set as an optional arg: https://github.com/googleapis/python-spanner-django/blob/11222db2f82fd50ca87010321ded0b39021eb884/spanner_dbapi/__init__.py#L34 But few lines lower it is checked for existence (thus, it's required, not optional): https://github.com/googleapis/python-spanner-django/blob/11222db2f82fd50ca87010321ded0b39021eb884/spanner_dbapi/__init__.py#L51-L52 It seems to be pointless, as this arg is only passed to Spanner client, and the original Spanner client can handle an omitted project: it'll use `google.auth.default()` function to designate the project id from the environment. With this, I'd propose to drop this check and use `project` arg in the way of the original Spanner client.

**instance and database args:**
They are optional by definition, but in fact both are required. Probably, they should become required in definition (the function signature will be `connect(instance, database, project=None, credentials_uri=None, user_agent=None):`), so these checks could be dropped:
https://github.com/googleapis/python-spanner-django/blob/11222db2f82fd50ca87010321ded0b39021eb884/spanner_dbapi/__init__.py#L53-L56

**credentials_uri arg:**
This arg looks divergent from how the original Spanner client is dealing with credentials:
https://github.com/googleapis/python-spanner/blob/b6b0348f5870f55c88b3cae44e229325fd755b26/google/cloud/spanner_v1/client.py#L123-L129

I'd propose to change this arg to use `google.auth.credentials.Credentials` class as it's done in the original Spanner client.

**Comment by c24t** [comment]
I agree with everything here, the null default args don't make and aren't required by DBAPI. And better to use `Credentials` than `credentials_uri`.
