### ISSUE TITLE
Cursor.executemany() hiding results up to the last one

### ISSUE THREAD

**Issue by IlyaFaer** [googleapis/python-spanner-django#518]
I think we have a bug in `Cursor.executemany()` method. Given the code it runs `Cursor.execute()` in a cycle, while `execute()` is actually replacing result of every previous call with a result from the last one.

So, if we, for example, will call `executemany()` with several reads, we'll get only results of the last one:

![Безымянный](https://user-images.githubusercontent.com/26030071/93857979-20a9a600-fcc4-11ea-81f3-5eb4069592e4.png)

But in fact both reads, with `SingerId=12` and with `SingerId=15`, were executed and we got results.

@c24t, we already have a proposition of how to deal with `executemany()` in the design doc, PTAL at `StreamedManyResultSets` section.

**Comment by skuruppu** [comment]
@IlyaFaer this was turning up on SLO dashboards so I put a priority on it. Please feel free to change the priority to what you want.

**Comment by IlyaFaer** [comment]
@c24t, are we okay to deal with it by adding the class `StreamedManyResultSets`, described in the design doc? I think the transactions retry is closing to the final state, so I'll do this one as well.

**Comment by c24t** [comment]
From @IlyaFaer's doc:

New `StreamedManyResultSets` class:
A wrap-around iterator, which iterates through several `StreamedResultSet()` as if they are all merged into a single iterator. This class is intended to be used by `Cursor.executemany()` method. After executing a query the method will save the resulting `StreamedResultSet()` object or `int` in case of an UPDATE operation into `StreamedManyResultSets`, before running the next query (which results will replace the results of the previous operation given the current implementation).

Thus, `Cursor.executemany()` will pump up all the resulting iterators or integers into a single `StreamedManyResultSets` iterator. While iterating through it with `fetchone()`, `fetchmany()` and `fetchall()`, users will be streaming through the results of every executed operation in the same order the operations were executed.

**Comment by IlyaFaer** [comment]
This one was fixed in the [python-spanner PR](https://github.com/googleapis/python-spanner/pull/181). Closing
