### ISSUE TITLE
Dedicated unit tests for django_spanner

### ISSUE THREAD

**Issue by c24t** [googleapis/python-spanner-django#541]
RIght now there's 0%(!) coverage for `django_spanner`, but django tests cover most of this dir. Do we need separate unit tests for `django_spanner`? This is probably a good idea, but may be redundant with existing django tests.

**Comment by vi3k6i5** [comment]
@skuruppu : what do you think ? should we add separate unit tests?

**Comment by skuruppu** [comment]
Yeah that's a really good question. I feel that we shouldn't just add redundant tests if the existing tests already test the code. Is there some way we can setup either the existing coverage checker or a new tool to report the coverage for the existing tests?

**Comment by vi3k6i5** [comment]
okay, I will work on using coverage report from existing django unit tests.
