### ISSUE TITLE
Incompatible with google-cloud-spanner 3.12 ->> UserWarning: The `rowcount` property is non-operational | Cannot update/delete model objects

### ISSUE THREAD

**Issue by rajjagesar** [googleapis/python-spanner-django#740]
#### Environment details

  - Programming language: Python
  - OS: MacOS Big Sur 11.4
  - Language runtime version: 3.8.9
  - Package version: Django 3.2.2 and 3.2.9 with django-cloud-spanner 3.0.0 and google-cloud spanner 3.12.0

#### Steps to reproduce

  1. Follow the "from scratch" documentation as outlined in the readme to the letter
  2. Instantiate and save a model, e.g.: `a = MyModel.objects.create(name="testname")`
  3. Try to delete the model with: `a.delete()`
  4. This will trigger the following error:
  ```
/Users/me/.pyenv/versions/3.8.9/envs/spannertest/lib/python3.8/site-packages/django/db/backends/utils.py:22: UserWarning: The `rowcount` property is non-operational. Request resulting rows are streamed by the `fetch*()` methods and can't be counted before they are all streamed.
  cursor_attr = getattr(self.cursor, attr)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/me/.pyenv/versions/3.8.9/envs/spannertest/lib/python3.8/site-packages/django/db/models/base.py", line 954, in delete
    return collector.delete()
  File "/Users/me/.pyenv/versions/3.8.9/envs/spannertest/lib/python3.8/site-packages/django/db/models/deletion.py", line 396, in delete
    count = sql.DeleteQuery(model).delete_batch([instance.pk], self.using)
  File "/Users/me/.pyenv/versions/3.8.9/envs/spannertest/lib/python3.8/site-packages/django/db/models/sql/subqueries.py", line 43, in delete_batch
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```
A similar error will be raised when trying to update the model: `a.name = "new name" & a.save()`.

**Comment by rajjagesar** [comment]
I have found the cause of this problem, I retested the scenario as described above with a downgraded version of the `google-cloud-spanner` dependency, reverting back to version 3.11.1 in stead of 3.12.0. This solves the problem, so I guess a breaking change has been made with the transition to version 3.12.

**Comment by vi3k6i5** [comment]
Hi @rajjagesar : I will look into what the issue is with the 3.12 and get back. Thanks for brining this to our notice.
