### ISSUE TITLE
Tests are not run in a transaction -> UserWarning: This method is non-operational in autocommit mode   return self.connection.commit()

### ISSUE THREAD

**Issue by rajjagesar** [googleapis/python-spanner-django#741]
- Programming language: Python
  - OS: Mac OS Big Sur 11.4
  - Language runtime version: 3.8.9
  - Package version: django-cloud-spanner 3.0.0, google-cloud-spanner 3.11.1 and Django 3.2.9

#### Steps to reproduce

  1. Follow the readme to the letter.
  2. Implement two different TestCases which use the setUpTestData() method to initialize objects
  3. Run tests with the `--keepdb` flag, since migrations on cloud spanner are long running operations
  4. This results in the following warning: 
 ```
/Users/me.pyenv/versions/3.8.9/envs/service/lib/python3.8/site-packages/django/db/backends/base/base.py:242: UserWarning: This method is non-operational in autocommit mode
  return self.connection.commit()
```
5. Observe that the records that are created in setUpTestData() are persisted to the testdatabase, which should not happen.
6. The consequence is that following testcases fail to run since due to (unique) constraint violations.

**Comment by vi3k6i5** [comment]
Hi @rajjagesar : can you share the test cases? I wanted to understand why the data should not be persisted in the db. Thanks
