### ISSUE TITLE
Django 4.2 support (Django 3.2 EOL April 2024)

### ISSUE THREAD

**Issue by chickahoona** [googleapis/python-spanner-django#853]
The pypi page here https://pypi.org/project/django-google-spanner/ shows at the moment the latest supported Django version is 3.2.
The problem is that Django 3.2 is EOL in 2 months (Source: https://www.djangoproject.com/download/), so people using your package have to decide eather to switch to another package or to run on an unsupported / potentially insecure version of Django.

So my question. Does this package already support maybe Django 4.2?

**Comment by cemoody** [comment]
i also ran into the same issue! i'll be watching this! thank you

**Comment by osean-man** [comment]
Is there any plan to update the package to support more recent versions of Django?

**Comment by jaz-la** [comment]
Hi folks, this really need to be prioritized, I know the EOL of Django 3.2 is end of April 2024, 
but it's not reasonable to release the new version at the end of April and lease users very limited time to upgrade django version.

**Comment by ankiaga** [comment]
Closing this as support for Django 4.2 has been released
